version: '3.1'
 
services:
   db:
     image: mysql:5.7
     volumes:
       - mysqldatavolume:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: easy
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     depends_on:
       - db
     image: wordpress:4.9.5
     volumes:
       - wordpressvolume:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: easy 
       WORDPRESS_DB_NAME: wordpress
     ports:
       - "8080:8080"
   nginx:
     image: nginx:1.13.12
     depends_on:
       - wordpress
     ports:
       - "80:80"
     build:
      context: .
      dockerfile: Dockerfile
volumes:
  mysqldatavolume:
  wordpressvolume:
  