version: '3.1'

services:
   db:
     image: mysql:latest
     volumes:
       - db-vol:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: easytoguess
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: eveneasier
 
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     volumes:
       - wp-vol:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: eveneasier
       WORDPRESS_DB_NAME: wordpress

   nginx:
     depends_on:
       - wordpress
     restart: always
     build:
       context: .
       dockerfile: Dockerfile-nginx
     ports:
       - "80:80"
volumes:
  db-vol:
  wp-vol: